apiVersion: v1
kind: Service
metadata:
  name: service-identity
spec:
  selector:
    app: service-identity
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-identity
spec:
  selector:
    matchLabels:
      app: service-identity
  replicas: 1
  template:
    metadata:
      labels:
        app: service-identity
    spec:
      containers:
        - name: server
          image: mdanko22/service-identity
          ports:
            - name: http
              containerPort: 8080

---