apiVersion: v1
kind: Service
metadata:
  name: service-payment
spec:
  selector:
    app: service-payment
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 31003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-payment
spec:
  selector:
    matchLabels:
      app: service-payment
  replicas: 1
  template:
    metadata:
      labels:
        app: service-payment
    spec:
      containers:
        - name: server
          image: mdanko22/service-payment
          ports:
            - name: http
              containerPort: 8083

---